### PR TITLE
Fix broken icons in Jenkins 2.333, replace PNGs with SVGs and use modern build status icons instead of balls

### PR DESCRIPTION
**Pull request by NotMyFault**
Originally, I was going ahead to fix the broken icons that referenced to paths that have been removed from core, e.g. in

but I've taken the opportunity to exchange the GIF and PNG icons with SVGs that were already added and got a rid of the ball colors in favor of the modernized build status:

### CODE REVIEW

**Comment by NotMyFault** [comment]
Heyo,

uh I'm not sure who maintains this plugin at the moment but I noticed that @batmat pushed some maintenance commits, would you mind taking a look at this PR?
I think, it would be great to have it available sometime around the next LTS, 2.332.1, which releases on March the 9th, which focuses a lot on UI improvements.
Thanks in advance!

**Comment by jtnord** [comment]
Why where the icons removed from core without replacement or aliasing? Icons are part of the API as much as java code and this would appear to be a regression.  How many other plugins are affected by this change?  (cloudbees-folder I recall also was tripped up as the GREY icon got removed (and then re-added) )

**Comment by NotMyFault** [comment]
> Why where the icons removed from core without replacement or aliasing? Icons are part of the API as much as java code and this would appear to be a regression?
> 
> Is this purely because the plugin was not using `l:icon` and if it was it would have been unaffected? (in which case I agree this is an issue in this plugin), if not then how many other plugins are affected by this change?

Core does overwrite icons in order of GIF -> PNG -> SVG (for Tango) -> ionicon, hence there's a blue arrow on the screenshot I attached, because the promotions plugin does now reference `icon-up` to place this icon which core provides.

Previously, the promotions plugin read the icon from its path
https://github.com/jenkinsci/promoted-builds-plugin/blob/7c3ab83aeb7909201d5af8e7e7adb7d0e1b85632/src/main/resources/hudson/plugins/promoted_builds/Promotion/index.jelly#L10-L12
The path does no longer exist, because the GIF and PNG sprites have been removed in favor of the SVG ones.

However, if a plugin does use the API of the icon class to place an icon, e.g. `icon-up` for l:task, l:icon or t:summary, they are unaffected by the icon removal, because the overwrite rule from above applies here and let core choose which icon to place, depending on the core version used.

The plugins affected by the removal are the ones that didn't use the API in the first place and relied on the icon path itself.

I published a [blog article](https://www.jenkins.io/doc/developer/views/icon-path-to-icon-class-migration/) at jenkins.io to provide a bit of guidance how to migrate from the usage of icon paths to the appropriate icon class API.

> (cloudbees-folder I recall also was tripped up as the GREY icon got removed (and then re-added) )

Yeah, but that was down to the icon not being registered in the first place, hence the icon overwrite couldn't apply here.

**Review by jtnord — APPROVED** [review]

**Review by jtnord — APPROVED** [review]

**Comment by batmat** [comment]
Looks like now the `master` branch is failing for some reason I don't have the time to look into now.

I have asked @car-roll to give it a try. I've given him access as a maintainer.

**Pull request merged**
