### PR TITLE
[JENKINS-31320] Layout broken as of 1.619+

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-31320](https://issues.jenkins-ci.org/browse/JENKINS-31320)

#### Screenshot 1024x768
jenkins-31320

@reviewbybees, specially @oleg-nenashev

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Web UIs are definitely not my topic, but :+1: and :bee:

**Comment by recena** [comment]
@oleg-nenashev Thanks. Who is the maintaner of this plugin?

**Comment by oleg-nenashev** [comment]
Technically it's me. I'll integrate the change into the new release ASAP.

**Comment by recena** [comment]
@oleg-nenashev It seems urgent for some users.

**Comment by oleg-nenashev** [comment]
Yep, thanks for fixing it! I'm the plugin's owner, so...
@reviewbybees done

**Pull request merged**
