### PR TITLE
[JENKINS-7739] - Fix the failing test

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This change fixes a test from #57 , which has been merged. The test is flappy, becase there was no rebuild of the dependency graph. In addition, test projects have been renamed for a better readability. 

@reviewbybees @FrantaM

### CODE REVIEW

**Comment by FrantaM** [comment]
That's interesting. The test _never_ failed on my computer.

**Comment by oleg-nenashev** [comment]
It depends on the execution speed of background Jenkins processes. Tests in Jenkins test-harness use such approach, so I think it's a reasonable change.. 

E.g. https://github.com/jenkinsci/jenkins/blob/fd83a285b3b1560ba19122ff33edc522de7027f0/test/src/test/java/hudson/model/ProjectTest.java#L367-L368

**Comment by amuniz** [comment]
Yes, the dependency graph seems to be running asynchronously (see [rebuildDependencyGraphAsync](https://github.com/jenkinsci/jenkins/blob/d331c12bbc2cf863efd39e0b135c584da364937a/core/src/main/java/jenkins/model/Jenkins.java#L3782)), so some race conditions could happen in this test.

:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done
I'm using my maintainer's hat to go forward

**Pull request merged**
