### PR TITLE
[JENKINS-31406] Jelly tag l:pane breaks the UI

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-31406](https://issues.jenkins-ci.org/browse/JENKINS-31406)

Related to [JENKINS-31320](https://issues.jenkins-ci.org/browse/JENKINS-31320)

@reviewbybees, specially @oleg-nenashev 

Easier to review if you use `w=1`

### BEFORE
captura el 2016-02-12 a las 10 12 19

### AFTER
captura el 2016-02-12 a las 10 06 12

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
LGTM :bee: . I hope to manually test and integrate it ASAP

**Comment by recena** [comment]
@oleg-nenashev Thanks.

**Comment by andresrc** [comment]
:bee:

**Comment by recena** [comment]
@reviewbybees done

**Comment by recena** [comment]
@andresrc @oleg-nenashev Please, find attached two screenshots with the result.

**Comment by oleg-nenashev** [comment]
Works for me locally

**Comment by recena** [comment]
@oleg-nenashev Thanks!

**Pull request merged**
