### PR TITLE
JENKINS-62817 Tables to divs compat

### PR DESCRIPTION
**Pull request by timja**
See [JENKINS-62817](https://issues.jenkins-ci.org/browse/JENKINS-62817).

cc @oleg-nenashev 

### Your checklist for this pull request

- [ ] Pull request title represents the changelog entry which will be used in Release Notes. JIRA issue is a part of the title (see existing PRs as examples)
- [ ] Please describe what you did. Short summary for reviewers. If the change involves WebUI, add screenshots 
- [ ] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org) or pull requests
- [ ] Test automation, if relevant. We expect autotests for all new features or complex bugfixes
- [ ] Documentation if relevant (new features). We want to use Documentation-as-Code, just put docs to README or to new Doc files
- [ ] Javadoc for new APIs. Any public/protected method is considered as API unless annotated by `Restricted` ([docs](https://kohsuke.org/access-modifier/apidocs/org/kohsuke/accmod/AccessRestriction.html)) 

### CC

@mention

### CODE REVIEW

**Comment by timja** [comment]
> Have you tested it on the current Jenkins core versions? Some top-level tables do not use the blockWrapper. If not, will retest manually before the merge

Oops, my bad, fixed.

Only tested on tables to divs, but there should be no change on regular core.

**Comment by timja** [comment]
ping @oleg-nenashev

**Comment by oleg-nenashev** [comment]
@timja do you need a release?

**Comment by timja** [comment]
> @timja do you need a release?

@oleg-nenashev yes please

**Pull request merged**
