### PR TITLE
[JENKINS-57877] - A Test Step to confirm the Builds have been Promoted. 

### PR DESCRIPTION
**Pull request by dernDren161**
As part of https://github.com/jenkinsci/promoted-builds-plugin/pull/128 this PR is for spot check/test automation for users to know that the upstream build is promotable/promoted. In the later Phases of this Project this step would probably be replaced by a Job Triggering action to label the Promotion. The expected function name for this step is : **addTestBadge**

_Note_: This step Would be seen effective after the introduction of other Promotion Steps so as to test their effectivity.
Link to relevant PR: [this](https://github.com/jenkinsci/promoted-builds-plugin/pull/128)
**Plan for the Step.**
pipeline{
      agent any       
      stages{
          stage('Self Promotion'){
            steps{      
               selfPromote(String job,int buildNumber,boolean b){
               **addTestBadge**(String job,int buildNumber)}
                     }
                                               }
              }

**Further Information**: The step is expected to give a LOGGER message on successful promotion of the previous Jobs.
Also Please Help rectify the code on any technical glitches.

_Test Results_:
- The module was compiled successfully and the plugin was hosted in the local server as well.
_Problem:_
- The pipeline option in the "New Item" list was not found to test the DSL step(Need suggestions on this).
_Report:_
- Though the module compiled correctly but however is not tested fully due to the above point(Need Suggestions)
 _Conclusion:_
- Need further Revisions on the Code itself and about testing.

See [JENKINS-57877](https://issues.jenkins-ci.org/browse/JENKINS-57877).

### Your checklist for this pull request

- [x] Pull request title represents the changelog entry which will be used in Release Notes. JIRA issue is a part of the title (see existing PRs as examples)
- [x] Please describe what you did. Short summary for reviewers. If the change involves WebUI, add screenshots 
- [x] Link to relevant [Jenkins JIRA issues](https://issues.jenkins-ci.org) or pull requests
- [ ] Test automation, if relevant. We expect autotests for all new features or complex bugfixes
- [ ] Documentation if relevant (new features). We want to use Documentation-as-Code, just put docs to README or to new Doc files
- [ ] Javadoc for new APIs. Any public/protected method is considered as API unless annotated by `Restricted` ([docs](https://kohsuke.org/access-modifier/apidocs/org/kohsuke/accmod/AccessRestriction.html)) 

### CC
@oleg-nenashev @jonbrohauge @bicschneider @MadsNielsen

### CODE REVIEW

**Comment by dernDren161** [comment]
> If this is a test step, it should be in the 'src/test/java' so that it appears in tests only.
> If this is intended to be a production code, it should be written and named accordingly

@oleg-nenashev Hi sorry for this implementation. I assume that this looks more like a production code. So this step should be placed before any other promotions i guess?! I'll reuse the PR with minor changes done to it. Will that work?

**Comment by oleg-nenashev** [comment]
@dernDren161 it will not work as is. You are still trying to add the test code to the production codebase which will go to users.  If you want to have `addTestBadge()` added to the production code, it should be renamed accordingly.  Also, Jelly files and documentation would need to be added so that the step becomes editable in the Snippet generator.

**Comment by dernDren161** [comment]
> @dernDren161 it will not work as is. You are still trying to add the test code to the production codebase which will go to users. If you want to have `addTestBadge()` added to the production code, it should be renamed accordingly. Also, Jelly files and documentation would need to be added so that the step becomes editable in the Snippet generator.

@oleg-nenashev Thanks for the response. What you suggested in the KT session PR was to have a test step before the promotion modules even begin to run? So i understand this PR method won't work and needs changes. So my requests to you:
1) Please share some code samples that address similar kind of testing since it would be way easier to find things out quickly, i could not spot them though i looked at many sources. It would save a lot of time as this is just a test step the main thing is yet to come. And also it took a lot of time for me to even frame this PR so plese share in some documentations for this.
2) Also i wanted to send a separate PR for the addPromotionBadge because by the time the test step PR gets accepted i could parallely work on the main refactorings for which i need the rest refactorings done from you in the KT session merged. I could then push my Promotion Conditions then. While i accept the addTestBadge should be the very first  step into doing things.

Thank You!

**Comment by oleg-nenashev** [comment]
> Please share some code samples that address similar kind of testing

1. Move the code to the `src/test` location
2. Create tests which invoke the step. There are plenty of examples , e.g. in https://github.com/jenkinsci/release-plugin/pull/22
3. Change extension to `@TestExtension`. https://github.com/jenkinsci/jenkins-test-harness/blob/master/src/main/java/org/jvnet/hudson/test/TestExtension.java

**Comment by dernDren161** [comment]
> > Please share some code samples that address similar kind of testing
> 
> 1. Move the code to the `src/test` location
> 2. Create tests which invoke the step. There are plenty of examples , e.g. in [jenkinsci/release-plugin#22](https://github.com/jenkinsci/release-plugin/pull/22)
> 3. Change extension to `@TestExtension`. https://github.com/jenkinsci/jenkins-test-harness/blob/master/src/main/java/org/jvnet/hudson/test/TestExtension.java

@oleg-nenashev ok Thank You so Much now it makes sense to me, all this while i thought testing meant testing Jobs from the DSL but no. Also just to reconfirm i guess sth similar to only :[ (this)](https://github.com/jenkinsci/release-plugin/blob/master/src/test/java/hudson/plugins/release/pipeline/ReleaseStepTest.java)  is required for now?

**Pull request closed without merging**
