### PR TITLE
 Add support for build wrappers in promotions

### PR DESCRIPTION
**Pull request by patrickschlebusch**
This PR adds support for build wrappers in the promotion processes. The build wrappers can also be specified for the promotions via JobDSL.
The build wrappers can be configured in a new "Promotion Environment" section of the promotion process configuration.

This is useful e.g. in order to be able to prepare an environment or inject secrets for the promotion.

There are a number of issues calling for this support:
* https://issues.jenkins-ci.org/browse/JENKINS-23977
* https://issues.jenkins-ci.org/browse/JENKINS-25526
* https://issues.jenkins-ci.org/browse/JENKINS-43656

For [JENKINS-14169](https://issues.jenkins-ci.org/browse/JENKINS-14169) this change might provide a workaround by allowing to inject environment vars for the promotion either from the configuration or by injecting them from a file passed to the promotion process.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@patrickschlebusch thanks!

**Comment by oleg-nenashev** [comment]
Looks great, thanks. Will ship it with the next release

**Comment by oleg-nenashev** [comment]
It will be released once I get https://github.com/jenkinsci/promoted-builds-plugin/pull/124 over the line. @patrickschlebusch  is the target core baseline fine with you?

**Comment by patrickschlebusch** [comment]
@oleg-nenashev Yes, all good! :+1:

**Comment by AndrGrig** [comment]
Hi,
Version 3.3 of Promoted Plugin isn't compatible with Jfrog Artifactory plugin 3.3.0.
If both plugins installed, We can't get list of Repositories from Artifactory.
Once we rolled back to Promoted Plugin to version 3.2 - everything works OK.
Also, Artifactory configuration shown duplicate.
Please advise.
@oleg-nenashev 
@patrickschlebusch

**Comment by AndrGrig** [comment]
@oleg-nenashev,
Hi Oleg, 
Thanks for you reply.
Exactly, both of these bugs were in our environment also.

**Pull request merged**
