### PR TITLE
[JENKINS-22679] Pass the target build parameters to the promotion build when the promotion build doesn't have its own parameters.

### PR DESCRIPTION
**Pull request by wgreven**
This should fix the regression introduced in 2.17.

### CODE REVIEW

**Comment by christ66** [comment]
@dnozay Ping. I think the PR looks good. The env-inject plugin should be logged as a different issue since JENKINS-22679 looks related to the build parameter option.

**Comment by dnozay** [comment]
@christ66 please go ahead and perform the release if you would like this in. I have a lot on my plate currently.

**Comment by JRLesser** [comment]
@christ66 @dnozay Was this ever released, or do you know when the plan to release this is?

**Comment by wgreven-ibr** [comment]
Hey guys, is there any chance this pull request will be merged this year? Otherwise I'm going to withdraw this pull request.

**Comment by JeanFred** [comment]
Echoing above questions :)

**Comment by branden** [comment]
:+1: Chiming in as someone who could really use this fix.

**Comment by JeanFred** [comment]
(Although it seems it would not fix my particular issue, as I need to pass variables obtained by EnvInject. [which #49 claimed to if I understood correctly])

**Comment by JeanFred** [comment]
Thanks for merging @christ66 !

**Comment by wgreven** [comment]
@christ66 Thank your very much!

**Pull request merged**
