### PR TITLE
[FIXED JENKINS-30212] - Add medium-sized icons (24x24)

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This change adds 24x24 icons for all promotion icon types

https://issues.jenkins-ci.org/browse/JENKINS-30212

@reviewbybees

### CODE REVIEW

**Comment by Vlatombe** [comment]
:bee:

**Comment by recena** [comment]
@oleg-nenashev Why both formats?

**Comment by oleg-nenashev** [comment]
@recena 
Do you mean *.gif and *.png? It seems to be a legacy from previous developers. I've just resized the previous 32x32 icons. OMO it makes sense to convert everything to PNG, but it should be done for all icon packs

**Comment by recena** [comment]
@oleg-nenashev Yes, I meant that. My preference is to use PNG (with transparency) and SVG. Anyways, :bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done (thanks for the reviews!)
This bug is not critical enough for the emergency release, so I'll kick-off together with something else on the next week

**Pull request merged**
